export const ADD_MEETING = "ADD_MEETING";
export const ADD_MEETING_SUCCESS = "ADD_MEETING_SUCCESS";
export const ADD_MEETING_FAILED = "ADD_MEETING_FAILED";

export const EDIT_MEETING = "EDIT_MEETING";
export const EDIT_MEETING_SUCCESS = "EDIT_MEETING_SUCCESS";
export const EDIT_MEETING_FAILED = "EDIT_MEETING_FAILED";
